# 10.错误处理与异常

## 10.1 关于错误处理

* **数据错误**
  * 在数字金额的一栏填上了商品名
* **系统错误**
  * 硬盘故障等明显的错误
* **程序错误**
  * 因调用了不存在的方法、弄错参数值或算法错误以及程序本身的缺陷产生的错误

对错误的处理：

* **排除错误的原因**
* **忽略错误**
  * 程序有一些无伤大雅错误时可以忽略
* **恢复错误发生前的状态**
  * 向用户提示错误，并指导用户如何操作
* **重试一次**
  * 曾经执行失败的程序，过一段时间后再重新执行可能就会成功
* **终止程序**
  * 只是一个人用的小程序，也许本来就没有必要做错误处理

对于可预期的错误，要注意：

* **是否破坏了输入的数据，特别是人工制作的数据**
* **是否可以对错误的内容及其原因做出相应的提示**

## 10.2 异常处理

错误：

```text
文件名：行号：in`方法名'：错误信息（异常类名）
    from 文件名：行号：in 方法名
    ···
```

ruby中的异常处理：

```text
begin
    a()
    b()
    c()
rescue
    错误处理
end
# a(),b(),c()中发生异常
```

## 10.3 异常处理的写法

Ruby中使用begin···rescue\`\`\`end语句描述一场处理。

```text
begin
    可能会发生异常的处理
rescue =>引用异常对象的变量
    发生异常时的处理
end
#异常发生时被自动赋值的变量
# $!  ： 最后发生的异常（异常对象）
# $@  ： 最后发生的异常的位置信息
```

异常对象的方法

| 方法名 | 意义 |
| :--- | :--- |
| class | 异常的种类 |
| message | 异常信息 |
| backtrace | 异常发生的位置信息（$@与$!.backtrace等价） |

```ruby
ltotal = 0
wtotal = 0
ctotal = 0
ARGV.each do |file|
	begin
		input = File.open(file)
		l = 0
		w = 0
		c = 0
		input.each_line do |line|
		# 无法打开文件时，程序会跳到rescue
		# rescue会提示错误，错误后继续处理下一个文件
			l += l
			c +=line.size
			line.sub!(/^\s+/," ")
			ary = line.split(/\s+/)
			w +=ary.size
		end
		input.close
		printf("%8d %8d %8d %s\n",l,w,c,file)
		ltotal +=l
		wtotal +=w
		ctotal +=c
	rescue =>ex
		print ex.message,"\n"
	end
end
printf("%8d %8d %8d %s\n",ltotal,wtotal,ctotal,"total")
```

![](../.gitbook/assets/image%20%28189%29.png)

## 10.4 后处理

不管是否发生异常都希望执行的处理，在Ruby中可以用ensure关键字来定义

```text
begin
    有可能发生异常的处理
rescue =>变量
    发生异常后的处理
ensure
    不管是否发生异常都希望执行的处理
end
```

## 10.5 重试

在rescue中使用retry后，begin以下的处理会再做一遍。

```ruby
# 如果指定了打不开的文件，程序有时候会陷入死循环
# 这种情况也可以添加一个判断
file = ARGV[0]
begin
	io = File.open("TheNewColossus.txt")
rescue
	sleep 10
	retry
end

data = io.read
io.close
puts data
```

![](../.gitbook/assets/image%20%28109%29.png)

## 10.6 rescue

**表达式1 rescue 表达式2**

等价于

```text
begin
    表达式1
rescue
    表达式2
end
```

```ruby
a1 = 123
a2 = "abc"
a3 = "123"

def intto(x)
	return Integer(x) rescue "not int"
end
p intto(a1)
p intto(a2)
p intto(a3)
```

![](../.gitbook/assets/image%20%28133%29.png)

## 10.7异常处理语法的补充

方法的异常处理

```text
def foo
    方法体
rescue => ex
    异常处理
ensure
    后处理
end
```

## 10.8 指定需要捕捉的异常

当存在多个种类的异常，且需要按异常的种类分别进行处理时，可以用多个rescue来分开处理

```text
begin
    可能发生异常的处理
rescue Exception1 或者Exception2 => 处理
    对Exception1或者Exception2的处理
rescue Exception3 =>变量
    对Exception3的处理
rescue
    对上述异常之外的处理
end
```

## 10.9 异常类

Ruby中所有的异常都是Exception类的子类，并根据程序错误的种类来定义相应的异常。

异常类的继承关系

![](../.gitbook/assets/image%20%2873%29.png)

```text
MyError = Class.new(StandardError)
# 等价于
class MyError < StandardError
end
```

## 10.10 主动抛出异常

使用raise方法可以使程序主动抛出异常。

* **raise信息**
  * 抛出RuntimeError异常，并在新生成的异常对象中设置作为信息的字符串。
* **raise异常类**
  * 抛出指定的异常
* **raise异常类，信息**
  * 抛出指定的异常，并在新生成的异常对象中设置作为信息的字符串
* **raise**
  * 在rescue外抛出RuntimeError。在ruscue中调用时，会再次抛出最后一次发生的异常（$!）

